In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy ', 'I am a good developer', 'understan the meaning of words', 'your videos are good']    

In [3]:
### Define the vocabulary size 
voc_size = 10000

In [4]:
## One hot Representation 

one_hot_repr = [one_hot(words,voc_size)for words in sent]
print(one_hot_repr)

[[611, 7960, 2298, 1826], [611, 7960, 2298, 3513], [611, 8080, 2298, 2655], [3329, 9431, 2686, 9880, 9657], [3329, 9431, 2686, 9880, 3419], [9111, 611, 2831, 2298, 9968], [565, 8876, 8825, 9880]]


In [6]:
## Word embedding representation 
from tensorflow.keras.layers import Embedding 

from tensorflow.keras.utils import pad_sequences

from tensorflow.keras.models import Sequential 



In [8]:
import numpy as np 

sent_len = 8 

embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)

print(embedded_docs)



[[   0    0    0    0  611 7960 2298 1826]
 [   0    0    0    0  611 7960 2298 3513]
 [   0    0    0    0  611 8080 2298 2655]
 [   0    0    0 3329 9431 2686 9880 9657]
 [   0    0    0 3329 9431 2686 9880 3419]
 [   0    0    0 9111  611 2831 2298 9968]
 [   0    0    0    0  565 8876 8825 9880]]


In [11]:
## Feasture Representation 

dim = 10

In [13]:
model = Sequential()

model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step


array([[[-0.01654246,  0.03972241,  0.00184386,  0.01310463,
          0.02334053, -0.04891509,  0.02554304,  0.03046357,
         -0.01859785,  0.00258138],
        [-0.01654246,  0.03972241,  0.00184386,  0.01310463,
          0.02334053, -0.04891509,  0.02554304,  0.03046357,
         -0.01859785,  0.00258138],
        [-0.01654246,  0.03972241,  0.00184386,  0.01310463,
          0.02334053, -0.04891509,  0.02554304,  0.03046357,
         -0.01859785,  0.00258138],
        [-0.01654246,  0.03972241,  0.00184386,  0.01310463,
          0.02334053, -0.04891509,  0.02554304,  0.03046357,
         -0.01859785,  0.00258138],
        [ 0.00711131, -0.00169539, -0.02327709, -0.03434889,
         -0.04925988,  0.01872082,  0.04741907,  0.0319689 ,
         -0.04686279,  0.02871627],
        [-0.00778853, -0.02349157, -0.00858481,  0.04351281,
          0.00459597,  0.02605217, -0.04278982, -0.00017052,
          0.03514138, -0.04166878],
        [ 0.0428478 ,  0.03141017, -0.02870067,  0.0